import * as fs from "fs";
import * as path from "path";
import { Client as ReplitObjectStorageClient } from "@replit/object-storage";

// Audio storage, swappable behind this interface so tests don't need live
// Replit infrastructure — same reasoning as replitAuth.ts's NODE_ENV=test
// bypass for the OIDC handshake. Never exposes a public URL either way:
// every read goes through GET /api/inbox/:id/audio (routes/voice.ts),
// which checks ownership via the SourceArtifact's userId before ever
// touching storage — per PRD Section 11, access-controlled, not public.
export interface AudioStorage {
  upload(objectKey: string, contents: Buffer): Promise<void>;
  download(objectKey: string): Promise<Buffer>;
  delete(objectKey: string): Promise<void>;
}

// Production backend. Client() auto-detects the bucket bound to the
// Repl — no bucket ID needed in config when actually running in a Repl.
class ReplitAudioStorage implements AudioStorage {
  private client = new ReplitObjectStorageClient();

  async upload(objectKey: string, contents: Buffer): Promise<void> {
    const { ok, error } = await this.client.uploadFromBytes(objectKey, contents);
    if (!ok) throw new Error(`Failed to upload audio: ${error?.message ?? "unknown error"}`);
  }

  async download(objectKey: string): Promise<Buffer> {
    const { ok, value, error } = await this.client.downloadAsBytes(objectKey);
    if (!ok) throw new Error(`Failed to download audio: ${error?.message ?? "unknown error"}`);
    // The SDK's downloadAsBytes returns a single-element Buffer array.
    return value[0];
  }

  async delete(objectKey: string): Promise<void> {
    const { ok, error } = await this.client.delete(objectKey);
    if (!ok) throw new Error(`Failed to delete audio: ${error?.message ?? "unknown error"}`);
  }
}

// Test-only backend: a gitignored local directory, so the isolation/
// retention test suite doesn't need live Replit object storage (which,
// like Replit's built-in Postgres, is only reachable from inside a Repl —
// see packages/db/README.md's note on that).
class LocalAudioStorage implements AudioStorage {
  private baseDir = path.join(__dirname, "..", "..", ".local-audio-storage");

  private resolvePath(objectKey: string): string {
    // objectKey is always generated by us (routes/voice.ts), never taken
    // directly from client input — normalized defensively anyway.
    const safeKey = objectKey.replace(/\.\./g, "");
    return path.join(this.baseDir, safeKey);
  }

  async upload(objectKey: string, contents: Buffer): Promise<void> {
    const filePath = this.resolvePath(objectKey);
    await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
    await fs.promises.writeFile(filePath, contents);
  }

  async download(objectKey: string): Promise<Buffer> {
    return fs.promises.readFile(this.resolvePath(objectKey));
  }

  async delete(objectKey: string): Promise<void> {
    await fs.promises.rm(this.resolvePath(objectKey), { force: true });
  }
}

let cachedStorage: AudioStorage | null = null;

export function getAudioStorage(): AudioStorage {
  if (!cachedStorage) {
    cachedStorage = process.env.NODE_ENV === "test" ? new LocalAudioStorage() : new ReplitAudioStorage();
  }
  return cachedStorage;
}
